service:
  build: ./service/src/github.com/orieken/go-rest
  links:
    - database
  ports:
    - "49200:49200"
  restart: always

database:
  image: mongo:3.0.4
  command: mongod --smallfiles --quiet