app:
  build: ./app
  command: npm start
  links:
    - service
  ports:
    - 49200:3000
service:
  build: ./service/src/github.com/orieken/go-rest
  command: /go/bin/go-rest
  links:
    - db
  ports:
    - 49201:7000
db:
  image: mongo:3.0.4
